import React, { useState, useCallback, useMemo } from 'react';
import { GlobeAltIcon, LoaderIcon, AlertTriangleIcon, SparklesIcon } from '../components/icons';
import { planTravel } from '../services/geminiService';
import { TravelItinerary } from '../types';
import { VoiceInputButton } from '../components/VoiceInputButton';

const TravelPlanner: React.FC = () => {
  const [destination, setDestination] = useState('');
  const [duration, setDuration] = useState('7');
  const [interests, setInterests] = useState('');
  const [itinerary, setItinerary] = useState<TravelItinerary | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = useCallback(async () => {
    if (!destination.trim() || !interests.trim()) {
      setError("Please provide a destination and your interests.");
      return;
    }
    setIsLoading(true);
    setError(null);
    setItinerary(null);
    try {
      const result = await planTravel({ destination, duration: `${duration} days`, interests });
      setItinerary(result);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "An unexpected error occurred.";
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  }, [destination, duration, interests]);

  const isGenerateDisabled = useMemo(() => isLoading || !destination.trim() || !interests.trim(), [isLoading, destination, interests]);

  return (
    <div className="h-full flex flex-col">
      <header className="flex items-center gap-4 mb-4">
        <GlobeAltIcon className="h-10 w-10 text-indigo-500 dark:text-indigo-400" />
        <h1 className="text-4xl font-bold text-gray-900 dark:text-slate-100">Travel Itinerary Planner</h1>
      </header>
      <p className="text-lg text-gray-600 dark:text-slate-400 mb-6 max-w-4xl">
        Plan your next trip with a detailed, day-by-day itinerary generated by AI.
      </p>

      <main className="flex-grow grid grid-cols-1 lg:grid-cols-3 gap-8 min-h-0">
        <div className="lg:col-span-1 bg-white/70 dark:bg-slate-800/50 backdrop-blur-md border border-gray-200 dark:border-slate-700 rounded-2xl p-6 shadow-xl dark:shadow-2xl dark:shadow-black/20 flex flex-col gap-6">
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-slate-100">Trip Details</h2>
          <div>
            <label htmlFor="destination" className="block text-sm font-medium text-gray-700 dark:text-slate-400 mb-2">Destination</label>
            <div className="relative">
                <input id="destination" type="text" value={destination} onChange={(e) => setDestination(e.target.value)} placeholder="e.g., Paris, France" className="w-full p-2 bg-gray-100 dark:bg-slate-900 border border-gray-300 dark:border-slate-600 rounded-lg pr-12 focus:ring-2 focus:ring-indigo-500 focus:bg-white dark:focus:bg-slate-800 focus:border-indigo-500 transition-all text-gray-900 dark:text-slate-100" />
                <div className="absolute inset-y-0 right-0 flex items-center pr-2"><VoiceInputButton onTranscript={setDestination} /></div>
            </div>
          </div>
           <div>
            <label htmlFor="duration" className="block text-sm font-medium text-gray-700 dark:text-slate-400 mb-2">Duration (in days)</label>
            <input id="duration" type="number" min="1" max="30" value={duration} onChange={(e) => setDuration(e.target.value)} className="w-full p-2 bg-gray-100 dark:bg-slate-900 border border-gray-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:bg-white dark:focus:bg-slate-800 focus:border-indigo-500 transition-all text-gray-900 dark:text-slate-100" />
          </div>
          <div>
            <label htmlFor="interests" className="block text-sm font-medium text-gray-700 dark:text-slate-400 mb-2">Interests & Activities</label>
            <div className="relative">
                <textarea id="interests" value={interests} onChange={(e) => setInterests(e.target.value)} placeholder="e.g., museums, hiking, local food, history" className="w-full p-2 bg-gray-100 dark:bg-slate-900 border border-gray-300 dark:border-slate-600 rounded-lg h-24 resize-none pr-12 focus:ring-2 focus:ring-indigo-500 focus:bg-white dark:focus:bg-slate-800 focus:border-indigo-500 transition-all text-gray-900 dark:text-slate-100" />
                <div className="absolute bottom-2 right-2"><VoiceInputButton onTranscript={(t) => setInterests(c => c + ' ' + t)} /></div>
            </div>
          </div>
          <button
            onClick={handleGenerate}
            disabled={isGenerateDisabled}
            className="w-full mt-auto py-3 px-6 bg-indigo-600 text-white font-semibold rounded-lg shadow-md shadow-indigo-500/20 hover:shadow-lg hover:shadow-indigo-500/40 hover:bg-indigo-500 disabled:bg-gray-600 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none transition-all duration-300 transform hover:-translate-y-1 flex items-center justify-center gap-2"
          >
            {isLoading ? <><LoaderIcon className="h-5 w-5" /> Planning...</> : <><SparklesIcon className="h-5 w-5" /> Plan Trip</>}
          </button>
        </div>

        <div className="lg:col-span-2 bg-white/70 dark:bg-slate-800/50 backdrop-blur-md border border-gray-200 dark:border-slate-700 rounded-2xl p-6 shadow-xl dark:shadow-2xl dark:shadow-black/20 flex flex-col min-h-0">
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-slate-100 mb-4">Your Itinerary</h2>
          <div className="w-full flex-grow bg-gray-50 dark:bg-slate-900 rounded-xl p-4 overflow-y-auto border border-gray-200 dark:border-slate-700">
            {isLoading && (
              <div className="flex flex-col items-center justify-center h-full gap-4">
                <LoaderIcon className="h-12 w-12 text-indigo-500 dark:text-indigo-400" />
                <p className="text-indigo-600 dark:text-indigo-300">Building your travel plan...</p>
              </div>
            )}

            {error && !isLoading && (
              <div className="flex items-center justify-center h-full">
                <div className="text-red-600 dark:text-red-400 bg-red-100 dark:bg-red-900/30 p-4 rounded-lg flex items-center gap-3">
                  <AlertTriangleIcon className="h-8 w-8 text-red-500 dark:text-red-400" />
                  <div><h3 className="font-bold">Error</h3><p className="text-sm">{error}</p></div>
                </div>
              </div>
            )}

            {!isLoading && !error && itinerary && (
              <div className="prose dark:prose-invert max-w-none">
                <h3 className="text-3xl font-bold text-indigo-600 dark:text-indigo-400 mb-2">{itinerary.destination}</h3>
                 <div className="flex flex-wrap gap-4 mb-6 text-sm not-prose">
                  <span className="bg-gray-200 dark:bg-slate-700 px-3 py-1 rounded-full text-gray-800 dark:text-slate-200"><b>Duration:</b> {itinerary.duration}</span>
                  <span className="bg-gray-200 dark:bg-slate-700 px-3 py-1 rounded-full text-gray-800 dark:text-slate-200"><b>Est. Budget:</b> {itinerary.budget}</span>
                </div>
                <div className="space-y-4">
                    {itinerary.dailyPlan.map((day) => (
                        <div key={day.day} className="bg-white dark:bg-slate-800/50 p-4 rounded-lg border border-gray-200 dark:border-slate-700 not-prose">
                            <h4 className="text-xl font-semibold text-gray-900 dark:text-slate-100 mb-2">Day {day.day}: {day.title}</h4>
                            <div className="pl-4 border-l-2 border-cyan-500">
                                <h5 className="font-bold text-gray-800 dark:text-slate-200">Activities:</h5>
                                <ul className="list-disc list-inside text-gray-700 dark:text-slate-300 mb-2">
                                    {day.activities.map((act, i) => <li key={i}>{act}</li>)}
                                </ul>
                                <h5 className="font-bold text-gray-800 dark:text-slate-200">Dining Suggestions:</h5>
                                <ul className="list-disc list-inside text-gray-700 dark:text-slate-300">
                                     {day.diningSuggestions.map((din, i) => <li key={i}>{din}</li>)}
                                </ul>
                            </div>
                        </div>
                    ))}
                </div>
              </div>
            )}
            
            {!isLoading && !error && !itinerary && (
              <div className="flex items-center justify-center h-full text-center text-gray-500 dark:text-slate-500">
                <div>
                  <GlobeAltIcon className="h-24 w-24 mx-auto mb-4" />
                  <p>Your amazing travel itinerary will appear here.</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default TravelPlanner;